# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(default=10, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeApp.Category'),
        ),
    ]
